// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuRGMIpXszTtouqRVg4fNBpgYLFoT15k',
    appId: '1:1057269249480:web:9c6fdecfbdaa33d59d3cfd',
    messagingSenderId: '1057269249480',
    projectId: 'elevateup-437bf',
    authDomain: 'elevateup-437bf.firebaseapp.com',
    storageBucket: 'elevateup-437bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvvhRqJbvyAQBmNovHWGmt_YT295j9hQc',
    appId: '1:1057269249480:android:a5fdda13571c268f9d3cfd',
    messagingSenderId: '1057269249480',
    projectId: 'elevateup-437bf',
    storageBucket: 'elevateup-437bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSdOQfjgkXWYdDNeDwXJ2bxjDO37ZLhIA',
    appId: '1:1057269249480:ios:42e3b2ad4b0f11709d3cfd',
    messagingSenderId: '1057269249480',
    projectId: 'elevateup-437bf',
    storageBucket: 'elevateup-437bf.appspot.com',
    iosClientId: '1057269249480-ovifluj3apimfpc56qkj34j1u1fue32m.apps.googleusercontent.com',
    iosBundleId: 'elevate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSdOQfjgkXWYdDNeDwXJ2bxjDO37ZLhIA',
    appId: '1:1057269249480:ios:42e3b2ad4b0f11709d3cfd',
    messagingSenderId: '1057269249480',
    projectId: 'elevateup-437bf',
    storageBucket: 'elevateup-437bf.appspot.com',
    iosClientId: '1057269249480-ovifluj3apimfpc56qkj34j1u1fue32m.apps.googleusercontent.com',
    iosBundleId: 'elevate.app',
  );
}
